### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by nixprosoft** [kohana/database#102]
Please give me a full example of correct transaction script for update N rows in one table.
The code below is doesn't pay attention to begin/commit commands and executing N queries.
P.S. [There](https://kohanaframework.org/3.2/guide/api/Database#begin) is no answer. There only "..." instead of the answer.

``` php
// in $items there is array of rows to update ($column_name => $column_data)
Database::instance()->begin();

try
{
    foreach ($items as $item) {
        $query = DB::update($this->_table);
        foreach ($item as $key => $val) {
            $query->set(array($key => $val));
        }
        $query->where($this->_table_primary_key, '=', (int)$item[$this->_table_primary_key]);
        $query->execute();
    }

    Database::instance()->commit();
    return count($items);
}
catch (Database_Exception $e)
{
    Database::instance()->rollback();
    return 0;
}

```

**Comment by enov** [comment]
@nixprosoft Your question is not clear to me. I did not understand what you're asking for.

> The code below is doesn't pay attention to begin/commit commands and executing N queries

Your code <u>is well doing a safe transaction</u> with the default instance of the database.

Regarding your update query, we can not give an answer to that, as it is specific to your application.

Kindly note that Kohana Github repo is not the place to seek support. You might want to head to [discourse.kohanaframework.org](http://discourse.kohanaframework.org) and ask your questions there.

Thanks!

**Comment by nixprosoft** [comment]
Thanks. I'm not searching support. I'm telling you - there is a bug. For example, if I comment out line:
//Database::instance()->commit();
the query will execute instead. How do you explain that?

**Comment by nixprosoft** [comment]
When I need to update N rows by transaction, I'm expecting 1 query to execute, not N. Am I correct?

**Comment by acoulton** [comment]
Transactions don't affect the number of queries that execute. They just wrap a set of queries together, so you can ask the DB to cancel (rollback) or save (commit) them as a batch.

If you call `$query->execute()` N times, with or without a transaction, then N queries will execute.

**Comment by enov** [comment]
As @acoulton has well stated, your queries are executed. Whether they are committed or not, that is a different story.

When you omit the explicit commit, the queries get rolled back at the end, when PHP closes the database connection. Except when you have persistent database connections, your queries will get committed because of subsequent `START TRANSACTION` calls, at the beginning of your script.

You probably know that returning `count($items)` does not return any actual execution info from the database. Your `Database` class might be fake, not doing real database stuff, and you can still have `count($items)` returned.

I have added some references. Allow me to politely close the issue. Reopen if you still think there is bug.

http://dev.mysql.com/doc/refman/5.7/en/commit.html
http://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

Cheers!

**Comment by nixprosoft** [comment]
My bad. Thanks for explanations.
Now I'm searching best practice to execute batch of queries (like INSERT N rows into one table with only one query) with QueryBuilder. Can you give me a link?
P.S. Sorry for off topic.

**Comment by acoulton** [comment]
SQL doesn't support multiple UPDATES in a single query, if you want to update N rows (with different values for each row) you'll need to execute multiple queries.
